FROM ubuntu
RUN apt -y update \
    && apt -y upgrade \
    && apt -y install wget \
    && apt -y install gnupg \
    && wget -q -O - https://repo.saltstack.com/apt/ubuntu/18.04/amd64/latest/SALTSTACK-GPG-KEY.pub | apt-key add - \
    && echo 'deb http://repo.saltstack.com/apt/ubuntu/18.04/amd64/latest bionic main' > /etc/apt/sources.list.d/saltstack.list \
    && apt -y update

# tzdata package requires configuration of timezone, below Env variable will make the installation non-interactive
# to disable the timezone configuration prompt
ENV DEBIAN_FRONTEND=noninteractive
RUN apt -y install salt-master salt-minion salt-ssh salt-cloud salt-api telnet iputils-ping \
    # Configure the minions to contact the master using the "master" hostname instead of the default "salt" hostname
    && sed 's/#master: salt/master: master/' /etc/salt/minion > /etc/salt/minion.tmp \
        && mv /etc/salt/minion.tmp /etc/salt/minion
        
CMD [ "/usr/bin/salt-minion", "-l", "debug" ]
